// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxkhtqezcyaqvjlbzzpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a2h0cWV6Y3lhcXZqbGJ6enB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMzY0MzYsImV4cCI6MjA3NTkxMjQzNn0.FKTd_iSQHWaiQDIEuX9fD-tt7cdzyhAeWmIjC6v8v-M";

// Get initial entreprise ID from localStorage
const getInitialEntrepriseId = (): string | null => {
  if (typeof window !== 'undefined') {
    return localStorage.getItem('current_entreprise_id');
  }
  return null;
};

const initialEntrepriseId = getInitialEntrepriseId();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: initialEntrepriseId ? { 'x-entreprise-id': initialEntrepriseId } : {},
  },
});

// To update headers after login, the app should call window.location.reload() 
// after setting current_entreprise_id in localStorage
